module.exports = {
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  jsxSingleQuote: false,
  trailingComma: 'all',
  bracketSpacing: true,
  arrowParens: 'always',
  htmlWhitespaceSensitivity: 'strict',
  quoteProps: 'preserve',
  plugins: ['prettier-plugin-tailwindcss'],
  endOfLine: 'lf',
};
